homeassistant:
  # Name of the location where Home Assistant is running
  name: Wardhead
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  
  #Domain customize
#  customize_domain:
#    script:
#      hidden: true
      
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest


# Enables configuration UI
config:

#Error log
logger:
  default: info
  logs:
    homeassistant.components.camera: error
    requests.packages.urllib3.connectionpool: error
    urllib3.connectionpool: error

#whitelist_external_dirs:
#    -/local/www/cam_captures/

# Floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml


ios:
  push:
    categories:
      - name: Doorbell
        identifier: 'doorbell'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

telegram_bot:
  - platform: polling
    api_key: 659527013:AAHsBUzv8peRhxxLRbixMG4Ww6qGz9Oj3N4
    allowed_chat_ids:
      - 696722934

notify:
#  - name: Pushbullet
#    platform: pushbullet
#    api_key: !secret pushbullet_api_key
  - platform: telegram
    name: thomasha_bot
    chat_id: 696722934

  - platform: html5
    name: wardhead_notify
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ssl_certificate: /home/homeassistant/dehydrated/certs/wardhead.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/wardhead.duckdns.org/privkey.pem
#  base_url: wardhead.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
    - belkin_wemo

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.1.194

#  nodered:
#    title: Node Red
#    icon: mdi:incognito
#    url: https://wardhead.duckdns.org:1880

# Media Players
media_player:
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: "amazon.co.uk"

# Text to speech
tts:
  platform: google

# Emulated Hue Bridge  
emulated_hue:
  host_ip: 192.168.1.194
  expose_by_default: false
  off_maps_to_on_domains:
    - script  
  
# MQTT Server
mqtt:
    discovery: true
    discovery_prefix: hassbian
    broker: localhost
    port: 1883
    username: 'pi'
    password: !secret mqtt_password

light:
  - platform: flux_led
    devices:
      192.168.1.209:
        name: "RGB LED Strip"
  - platform: mqtt_json
    name: "Wardhead LED 1"
    command_topic: "wardhead/led1/set"
    state_topic: "wardhead/led1"
    effect: true
    effect_list:
      - animations
      - bpm  
      - blendwave
      - beatwave
      - blur
      - candy cane
      - confetti
      - confetti 2
      - confetti pal
      - cyclon rainbow
      - dots
      - dotbeat
      - easing
      - every n example
      - fill grad
      - fire
      - glitter
      - inoise8 mover
      - inoise8 pal
      - juggle
      - lightning
      - noise
      - noise 16 1
      - noise 16 2
      - noise 16 3
      - one sine pal
      - palette cross fade
      - police all
      - police one
      - rainbow
      - rainbow march
      - rainbow beat
      - rainbow with glitter
      - ripple
      - ripple pal
#      - sinelon
      - solid
      - template
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

input_number:
  wardhead_led1_animation_speed:
    name: "Wardhead LED 1 Animation Speed"
    initial: 150
    min: 1
    max: 150
    step: 10

# Max! Eq-3
maxcube:
  gateways:
    - host: !secret maxcube_url


binary_sensor: !include binary_sensor.yaml

camera: !include camera.yaml

device_tracker: !include device_tracker.yaml
        
input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

sensor: !include sensor.yaml

switch: !include switch.yaml
  
timer: !include timers.yaml

zone: !include zones.yaml

        
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
