default_view:
    view: yes
    name: Controls
    icon: mdi:home
    entities:
      - group.tv
      - group.lights
      - group.linknode
      - group.heating
      - group.workshop
      - sensor.time
      - sensor.yr_symbol
      - sensor.Version
      - sensor.ha_release
      - sun.sun
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daytime_high_temperature
      - sensor.dark_sky_overnight_low_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_precip_intensity
      - binary_sensor.doorbell
      - sensor.pi_cpu_temperature
      - device_tracker.daddy
      - device_tracker.iphone
#      - sensor.daddy_internal
      - binary_sensor.flic_80e4da728dab
      - media_player.living_room
      - media_player.kitchen
      - media_player.everywhere
#      - camera.front_door_camera
      - camera.back_garden_camera
      - camera.kitchen_camera
      - camera.wardhead_camera
      - group.doors
      - group.motion
#      - script.test_telegram
#      - input_boolean.test

doors:
  name: Doors
  entities:
    - binary_sensor.front_door
    - binary_sensor.living_room_patio_door

motion:
  name: Motion Detectors
  entities:
    - binary_sensor.front_hall_motion

workshop:
    name: Workshop
    entities:
      - switch.workshop_socket
      - switch.workshop_lamp

hudl:
    name: Hudl
    entities:
      - camera.hudl
      - sensor.hudl_battery_level
      - sensor.hudl_motion
  
scripts:
    name: Scripts
    entities:
      - script.turn_tv_on
      - script.turn_tv_off
      - script.alexa_tv_toggle
      - script.dummy_script
      - script.alexa_boolean_reset

lights:
    name: Lights
    entities:
      - switch.wall_lights
      - switch.big_light
      - switch.bar_light
      - switch.the_lamp
      - switch.front_hall
      - switch.outside_front
tv:
    name: TV
    control: hidden
    entities:
      - switch.projector_socket
      - switch.tv_projector
      - switch.tv_plug
      - switch.tv_bluray
      - script.turn_tv_on
      - script.turn_tv_off
      
linknode:
    name: Linknode
    entities:
      - switch.speakers
#      - switch.relay2
#      - switch.relay3
#      - switch.relay4

heating:
    name: Heating
    control: hidden
    entities:
      - binary_sensor.heating
      - binary_sensor.heating_controller
      - input_boolean.heating_override
      - input_boolean.heating_boost

input_boolean:
    name: Input Boolean
    control: hidden
    entities:
      - input_boolean.alexa_tv_toggle
      - input_boolean.alexa_toggle_call
      - input_boolean.dummy_boolean
      - input_boolean.heating_boost
      - input_boolean.heating_override
      - input_boolean.thomas_away
      - input_boolean.caroline_away
      - input_boolean.test

climate:
    view: yes
    name: Climate
    icon: mdi:radiator
    entities:
      - group.climate_downstairs
      - group.climate_upstairs
      - group.heating
      
climate_downstairs:
    name: Climate Downstairs
    icon: mdi:radiator
    entities:
      - climate.living_room_living_room_wall_thermostat
      - climate.living_room_dining_radiator
      - climate.living_room_tv_radiator
      - climate.hall_hall_wall_thermostat
      - climate.hall_entrance_radiator
      - climate.hall_hall_radiator
      - climate.spare_room_spare_room_radiator
      - climate.kitchen_kitchen_wall_thermostat
      - climate.kitchen_kitchen_radiator
      - climate.downstairs_master_bedroom_downstairs_master_radiator

climate_upstairs:
    name: Climate Upstairs
    icon: mdi:radiator
    entities:
      - climate.seamus_bedroom_seamus_radiator
      - climate.upstairs_master_bedroom_upstairs_master_wall_thermostat
      - climate.upstairs_master_bedroom_upstairs_master_radiator

automation:
    view: yes
    name: Automation
    entities:
      - group.flic
      - group.input_boolean
      - group.all_automations
      - timer.boost_timer
      - timer.front_hall_timer

info:
    view: yes
    name: Information
    entities:
      - camera.ip_info
      - camera.central_heating_program
      - camera.max_eq_info
      - sensor.google_wifi_current_version
      - sensor.google_wifi_new_version
      - sensor.google_wifi_uptime
      - sensor.google_wifi_last_restart
      - sensor.google_wifi_local_ip
      - sensor.google_wifi_status

flic:
    name: Flic Button Modes
    entities:
      - input_select.flic_button_mode_single
      - input_select.flic_button_mode_double
      - input_select.flic_button_mode_held

leds:
    view: yes
    name: LEDs
    entities:
     - light.rgb_led_strip
     - light.wardhead_led_1
     - input_number.wardhead_led1_animation_speed

test:
    name: Test
    entities:
      - timer.boost_timer
      - input_boolean.test      
